### ISSUE TITLE
导出选项没有记住之前已经勾选的选项

### ISSUE THREAD

**Issue by ghost** [zhyhang/export-jar#10]
![image](https://user-images.githubusercontent.com/43258262/164369615-0d8fda2d-6324-4b50-9ca2-d5dc7c60562f.png)

**Comment by zhyhang** [comment]
好的，谢谢反馈。我抽时间加一下。

**Comment by zhyhang** [comment]
@chazhongbao Hi，已经升级，可记住上次的导出选项。plugin包已经上传，请在idea的插件市场中更新到2.4.0版本。
