### ISSUE TITLE
能否支持选定文件某些文件，而不是jar

### ISSUE THREAD

**Issue by sdhzwc** [zhyhang/export-jar#18]
针对于Tomcat部署部分文件导出，可以选定某些class文件导出，而不是jar导出，例如
![image](https://github.com/zhyhang/export-jar/assets/46134044/b19ae95c-a0e8-46b7-9aeb-e618c1e7e507)
导出target/classes/com/wfu/dao/UserMapper.class文件，类似支持export-file的方式

**Comment by sdhzwc** [comment]
增加导出的多样性
直接导出文件就不需要编译了，大致分为两种情况：
1、导出文件夹下的文件夹，例如我们选择dao,导出文件路径就行：{自己选择的文件保存路径}/{项目名}/{target下面选中的文件夹所有}   （桌面/xx项目/target/classes/com/wfu/dao/all.class）
2、导出文件夹下的文件，例如我们选择dao下xx.class,导出文件路径就行：{自己选择的文件保存路径}/{项目名}/{target下面选中的文件}   （桌面/xx项目/target/classes/com/wfu/dao/xx.class）

**Comment by zhyhang** [comment]
理解你的需求，我抽时间看一下。

**Comment by sdhzwc** [comment]
> 理解你的需求，我抽时间看一下。

好的，谢谢！

**Comment by sdhzwc** [comment]
您好，作者！这个实现起来复杂吗？
我也拉取了相关代码自己调试，改了几行代码基本上就起不来了，还是这方面经验还是太少了😂idea仓库也有一个插件支持我说的那种导出，就是不支持您左侧的选择列表

**Comment by zhyhang** [comment]
我最近自己的时间较少。其实你需求，到class目录，用winrar导出更合适。

**Comment by sdhzwc** [comment]
> 我最近自己的时间较少。其实你需求，到class目录，用winrar导出更合适。

我最近也在寻找替代品，就是不太好找您左侧设计的选中按钮，我感觉那个是一个很棒的设计。
