### ISSUE TITLE
怎么增加未受版本控制的文件导出呢？

### ISSUE THREAD

**Issue by changshunxu520** [zhyhang/export-jar#21]
大佬好，我希望在导出时获取到未受版本控制的代码，同样也导出到我的jar包中，这个如何实现呢？目前好像不能导出
![image](https://github.com/zhyhang/export-jar/assets/16171624/4f1cc549-da4f-437b-ba03-5cca09ade7b7)

**Comment by zhyhang** [comment]
我先看一下问题，若确认抽时间完善

**Comment by changshunxu520** [comment]
> 我先看一下问题，若确认抽时间完善

谢谢大佬，我 Fork 了代码，但对 Idea 的 API 确实不熟悉，虽然我能跑起来。但有些想实现的代码不熟悉 API 确实做不到，🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by zhyhang** [comment]
我检查了代码，idea给的扩展能力，传递的changes的确只有versioned文件，未在版本控制的文件未传给插件。现在变通的方式，可在project视图的列表中选择要导入的文件（可以是版本控制的也可以是未控制的），然后export  jar...

**Comment by changshunxu520** [comment]
> 我检查了代码，idea给的扩展能力，传递的changes的确只有versioned文件，未在版本控制的文件未传给插件。现在变通的方式，可在project视图的列表中选择要导入的文件（可以是版本控制的也可以是未控制的），然后export jar...

那好吧，感谢

**Comment by zhyhang** [comment]
> > 我检查了代码，idea给的扩展能力，传递的changes的确只有versioned文件，未在版本控制的文件未传给插件。现在变通的方式，可在project视图的列表中选择要导入的文件（可以是版本控制的也可以是未控制的），然后export jar...
> 
> 那好吧，感谢

我已计划重构export jar from local changes，也就一起支持你的需求了，估计要到下月会发一个版本。这个issue可以先保持打开。

**Comment by zhyhang** [comment]
@changshunxu520  
重构了一下export jar from local changes 功能，并上传插件文件到github上，可下载安装（未发布到市场，下载zip文件后，在idea的plugins界面，选择install from disk...）试一试。
https://github.com/zhyhang/export-jar/blob/dev-2.5.3/Handy%20Export%20Jar-2.5.3.zip
在Build菜单->Export Jar from Local Changes，会直接弹出版本变更列表，其中可以选择un-versioned文件并导出（去掉原来还要先到commit界面再弹出导出界面，现在直接在导出界面选择）。
另外，原来commit界面，下拉按钮的Export Jar...还保留，且逻辑没变（不支持导出un-versioned）。
有问题，请反馈。

**Comment by changshunxu520** [comment]
@zhyhang 感谢大佬的处理，我会在明天测试一下，最近有点忙，没来及

**Comment by changshunxu520** [comment]
@zhyhang 感谢处理，我已验证可以看到未受版本控制的文件
