### ISSUE TITLE
插件2.5.x版本在IntelliJ IDEA2023.x版本SVN导出会跳转到提交代码变更界面

### ISSUE THREAD

**Issue by Undest2000** [zhyhang/export-jar#24]
IntelliJ IDEA2023.x版本(测试过的有专业版2023.3.6、社区版2023.2.5):
插件从2.4.1版本更新到2.5.1/2.5.2后，在SVN版本管理界面选择导出jar包会跳转到提交代码变更界面，误以为点击后会导出，实际上真的会把文件提交到SVN:
插件v2.5.1/v2.5.2,点击确认后会真的提交文件到SVN：
![image](https://github.com/zhyhang/export-jar/assets/81337106/cd1e42d1-71b2-4479-af6c-fca6ef776136)
插件v2.4.1,点击后可以正常导出jar包:
![image](https://github.com/zhyhang/export-jar/assets/81337106/6bd193e4-d9c0-49fb-b959-931891a7aa81)
我在之前的issue里看到了作者大大您提及会在2.5.3版本修改回之前的界面？

**Comment by zhyhang** [comment]
在2.5.x版本理论不会出现这种情况，export jar是作为扩展点放到commit的界面的。就是第一张截图，应该在“提交按钮”下拉出“export Jar...”，不要直接选择提交
